# Generated by Django 5.2.13 on 2026-04-29 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_categoria_libros_libro_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='bibliografia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='catalogo.libro'),
        ),
    ]
