# Generated by Django 5.2.13 on 2026-05-05 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_autor_bibliografia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='bibliografia',
            new_name='biografia',
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.libro'),
        ),
    ]
