# Generated by Django 5.2.13 on 2026-05-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_rename_bibliografia_autor_biografia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='fecha_nacimiento',
        ),
    ]
